-- Create table
create table ""UNIMEDLF""."AspNetRoles"
(
  "Id"               NVARCHAR2(450) not null,
  "Name"             NVARCHAR2(256),
  "NormalizedName"   NVARCHAR2(256),
  "ConcurrencyStamp" NVARCHAR2(2000)
)
tablespace INFOMED_DADOS
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate indexes 
create unique index ""UNIMEDLF""."RoleNameIndex" on ""UNIMEDLF""."AspNetRoles" ("NormalizedName")
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table ""UNIMEDLF""."AspNetRoles"
  add constraint "PK_AspNetRoles" primary key ("Id")
  using index 
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );


-- Create table
create table ""UNIMEDLF""."AspNetUsers"
(
  "Id"                     NVARCHAR2(450) not null,
  "FirstName"              NVARCHAR2(2000),
  "LastName"               NVARCHAR2(2000),
  "UserName"               NVARCHAR2(256),
  "NormalizedUserName"     NVARCHAR2(256),
  "Email"                  NVARCHAR2(256),
  "NormalizedEmail"        NVARCHAR2(256),
  "EmailConfirmed"         NUMBER(1) not null,
  "PasswordHash"           NVARCHAR2(2000),
  "SecurityStamp"          NVARCHAR2(2000),
  "ConcurrencyStamp"       NVARCHAR2(2000),
  "PhoneNumber"            NVARCHAR2(2000),
  "PhoneNumberConfirmed"   NUMBER(1) not null,
  "TwoFactorEnabled"       NUMBER(1) not null,
  "LockoutEnd"             TIMESTAMP(7) WITH TIME ZONE,
  "LockoutEnabled"         NUMBER(1) not null,
  "AccessFailedCount"      NUMBER(10) not null,
  "RefreshToken"           NVARCHAR2(2000),
  "RefreshTokenExpiryTime" TIMESTAMP(7) WITH TIME ZONE
)

 

-- Create/Recreate indexes 
create index ""UNIMEDLF""."EmailIndex" on ""UNIMEDLF""."AspNetUsers" ("NormalizedEmail");

create unique index ""UNIMEDLF""."UserNameIndex" on ""UNIMEDLF""."AspNetUsers" ("NormalizedUserName")
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table ""UNIMEDLF""."AspNetUsers"
  add constraint "PK_AspNetUsers" primary key ("Id")
  using index 
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );


  -- Create table
-- Create table
create table ""UNIMEDLF""."AspNetRoleClaims"
(
  "Id"         NUMBER(10) generated by default on null as identity,
  "RoleId"     NVARCHAR2(450) not null,
  "ClaimType"  NVARCHAR2(2000),
  "ClaimValue" NVARCHAR2(2000)
)
tablespace INFOMED_DADOS
  pctfree 10
  initrans 1
  maxtrans 255;
-- Create/Recreate indexes 
create index ""UNIMEDLF""."IX_AspNetRoleClaims_RoleId" on ""UNIMEDLF""."AspNetRoleClaims" ("RoleId")
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints 
alter table ""UNIMEDLF""."AspNetRoleClaims"
  add constraint "PK_AspNetRoleClaims" primary key ("Id")
  using index 
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ""UNIMEDLF""."AspNetRoleClaims"
  add constraint "FK_AspNetRoleClaims_AspNetRoles_RoleId" foreign key ("RoleId")
  references ""UNIMEDLF""."AspNetRoles" ("Id") on delete cascade;


-- Create table
create table ""UNIMEDLF""."AspNetUserClaims"
(
  "Id"         NUMBER(10) generated by default on null as identity,
  "UserId"     NVARCHAR2(450) not null,
  "ClaimType"  NVARCHAR2(2000),
  "ClaimValue" NVARCHAR2(2000)
)
tablespace INFOMED_DADOS
  pctfree 10
  initrans 1
  maxtrans 255;
-- Create/Recreate indexes 
create index ""UNIMEDLF""."IX_AspNetUserClaims_UserId" on ""UNIMEDLF""."AspNetUserClaims" ("UserId")
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints 
alter table ""UNIMEDLF""."AspNetUserClaims"
  add constraint "PK_AspNetUserClaims" primary key ("Id")
  using index 
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ""UNIMEDLF""."AspNetUserClaims"
  add constraint "FK_AspNetUserClaims_AspNetUsers_UserId" foreign key ("UserId")
  references ""UNIMEDLF""."AspNetUsers" ("Id") on delete cascade;



-- Create table
create table ""UNIMEDLF""."AspNetUserLogins"
(
  "LoginProvider"       NVARCHAR2(450) not null,
  "ProviderKey"         NVARCHAR2(450) not null,
  "ProviderDisplayName" NVARCHAR2(2000),
  "UserId"              NVARCHAR2(450) not null
)
tablespace INFOMED_DADOS
  pctfree 10
  initrans 1
  maxtrans 255;
-- Create/Recreate indexes 
create index ""UNIMEDLF""."IX_AspNetUserLogins_UserId" on ""UNIMEDLF""."AspNetUserLogins" ("UserId")
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints 
alter table ""UNIMEDLF""."AspNetUserLogins"
  add constraint "PK_AspNetUserLogins" primary key ("LoginProvider", "ProviderKey")
  using index 
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ""UNIMEDLF""."AspNetUserLogins"
  add constraint "FK_AspNetUserLogins_AspNetUsers_UserId" foreign key ("UserId")
  references ""UNIMEDLF""."AspNetUsers" ("Id") on delete cascade;


  -- Create table
create table "UNIMEDLF"."AspNetUserRoles"
(
  "UserId" NVARCHAR2(450) not null,
  "RoleId" NVARCHAR2(450) not null
)
tablespace INFOMED_DADOS
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate indexes 
create index "UNIMEDLF".IX_AspNetUserRoles_RoleId on "UNIMEDLF"."AspNetUserRoles" ("RoleId")
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table "UNIMEDLF"."AspNetUserRoles"
  add constraint "PK_AspNetUserRoles" primary key ("UserId", "RoleId")
  using index 
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table "UNIMEDLF"."AspNetUserRoles"
  add constraint "FK_AspNetUserRoles_AspNetRoles_RoleId" foreign key ("RoleId")
  references "UNIMEDLF"."AspNetRoles" ("Id") on delete cascade;
alter table "UNIMEDLF"."AspNetUserRoles"
  add constraint "FK_AspNetUserRoles_AspNetUsers_UserId" foreign key ("UserId")
  references "UNIMEDLF"."AspNetUsers" ("Id") on delete cascade;

  -- Create table
create table "UNIMEDLF"."AspNetUserTokens"
(
  "UserId"        NVARCHAR2(450) not null,
  "LoginProvider" NVARCHAR2(450) not null,
  "Name"          NVARCHAR2(450) not null,
  "Value"         NVARCHAR2(2000)
)
tablespace INFOMED_DADOS
  pctfree 10
  initrans 1
  maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints 
alter table "UNIMEDLF"."AspNetUserTokens"
  add constraint "PK_AspNetUserTokens" primary key ("UserId", "LoginProvider", "Name")
  using index 
  tablespace INFOMED_DADOS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table "UNIMEDLF"."AspNetUserTokens"
  add constraint "FK_AspNetUserTokens_AspNetUsers_UserId" foreign key ("UserId")
  references "UNIMEDLF"."AspNetUsers" ("Id") on delete cascade;
